# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-25 15:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_phone', '0011_auto_20180129_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructions',
            name='language',
            field=models.CharField(blank=True, choices=[(b'en', 'English'), (b'ceb', 'Bisaya')], default='', max_length=8, validators=[django.core.validators.RegexValidator('^(|en|ceb)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='language',
            field=models.CharField(blank=True, choices=[(b'en', 'English'), (b'ceb', 'Bisaya')], default='', max_length=8, validators=[django.core.validators.RegexValidator('^(|en|ceb)$')]),
        ),
    ]
